version: '3.8'

services:

  mysql1:
    image: mysql:8
    container_name: mysql1
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: shop1
      TZ: 'Europe/Belgrade'
    volumes:
      - ./data/mysql1/conf.d:/etc/mysql/conf.d
      - ./data/mysql1/log:/var/log/mysql
      - ./data/mysql1/init:/docker-entrypoint-initdb.d
      - ./data/mysql1/files:/var/lib/mysql-files
      - ./data/mysql1/data:/var/lib/mysql
    command: --character-set-server=utf8 --collation-server=utf8_slovenian_ci --init-connect='SET NAMES UTF8;'
    networks:
      - network
    restart: always

  mysql2:
    image: mysql:8
    container_name: mysql2
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: shop2
      TZ: 'Europe/Belgrade'
    volumes:
      - ./data/mysql2/conf.d:/etc/mysql/conf.d
      - ./data/mysql2/log:/var/log/mysql
      - ./data/mysql2/init:/docker-entrypoint-initdb.d
      - ./data/mysql2/files:/var/lib/mysql-files
      - ./data/mysql2/data:/var/lib/mysql
    command: --character-set-server=utf8 --collation-server=utf8_slovenian_ci --init-connect='SET NAMES UTF8;'
    networks:
      - network
    restart: always

  mysql3:
    image: mysql:8
    container_name: mysql3
    ports:
      - "3309:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: shop3
      TZ: 'Europe/Belgrade'
    volumes:
      - ./data/mysql3/conf.d:/etc/mysql/conf.d
      - ./data/mysql3/log:/var/log/mysql
      - ./data/mysql3/init:/docker-entrypoint-initdb.d
      - ./data/mysql3/files:/var/lib/mysql-files
      - ./data/mysql3/data:/var/lib/mysql
    command: --character-set-server=utf8 --collation-server=utf8_slovenian_ci --init-connect='SET NAMES UTF8;'
    networks:
      - network
    restart: always

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    environment:
      TZ: 'Europe/Belgrade'
    networks:
      - network
    restart: always

networks:
  network:

volumes:
  mysql1-data:
  mysql2-data:
  mysql3-data:
