spring:
  sql:
    init:
      mode: always
      schema-locations: classpath:db/schema.sql

  jpa:
    hibernate:
      ddl-auto: none # Prevents Hibernate from touching our schema
    show-sql: true

  cache:
    type: redis
    redis:
      time-to-live: 60000 # TTL: data is stored for 1 minute in cache.

  data:
    redis:
      host: redis
      port: 6379
      repositories:
        enabled: false

server:
  port: 8080