apiVersion : v1
kind : Secret
metadata:
  name : mysql-secrets # we can give any name
type: Opaque
data:
  password : cm9vdA== # base64 encoded

# Secrets are stored in etcd the Kubernetes internal database which is unencrypted by default.
# If someone has access to the cluster or etcd, they can easily read them