apiVersion: v1
kind: Service
metadata:
  name: mysql-shop
  labels:
    app: mysql-shop
spec:
  ports:
    - port: 3306
  clusterIP: None  # Headless service for stable DNS
  selector:
    app: mysql-shop
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-shop
spec:
  serviceName: mysql-shop
  replicas: 5 # When Changing number of mysql replicas change also number in app-deployment.yml !!!
  selector:
    matchLabels:
      app: mysql-shop
  template:
    metadata:
      labels:
        app: mysql-shop
    spec:
      containers:
        - name: mysql
          image: mysql:8
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: root
            - name: MYSQL_DATABASE
              value: shop
          volumeMounts:
            - name: mysql-storage
              mountPath: /var/lib/mysql
  volumeClaimTemplates:
    - metadata:
        name: mysql-storage
      spec:
        storageClassName: standard
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 300Mi