apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
spec:
  selector:
    matchLabels:
      app: redis
  replicas: 1 # Runs 1 Redis pod.
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:latest
          ports:
            - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: redis # Creates a Kubernetes Service named redis.
spec:
  ports:
    - port: 6379 # Exposes port 6379 inside the cluster.
  selector:
    app: redis

#    All app replicas share the same cache state
#    You avoid cache duplication per instance
#    Useful for things like: login tokens, user sessions, product info, rate-limiting, etc.
#   All Spring Boot replicas (pods) are connecting to that same Redis instance